server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/covid
    username: root
    password: password

  properties:
    hibernate:
      format_sql: true
